project:
  type: book
  output-dir: docs

book:
  title: ""
  author: ""
  date: ""
  chapters:
    - index.qmd
    - intro.qmd
    - gramatica.qmd
    - verbos.qmd
    - vocabulario.qmd
    - expressoes.qmd
    - dez_verbos.qmd
    - exercicio.qmd
    - dizer.qmd
    

bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, custom-light.scss]
      dark: [darkly, custom-dark.scss]
    default-mode: dark
    mainfont: system-ui
    fontsize: 1.1em
    toc: true
    toc-depth: 3
    code-copy: true
    smooth-scroll: true
  pdf:
    documentclass: scrreprt

editor: visual